routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Auditoire::getBilan();
    return view('test');
});


Route::prefix('comptabilite')->group(function(){
	Route::name('comptabilite.')->group(function () {
		Route::get('/','Comptabilite\DashboardController@index')->name('index');
		Route::get('/auditoire/{auditoire}','Comptabilite\DashboardController@getListStudent')->name('getListStudent');
		
		Route::get('/autorise/{etudiant}','Comptabilite\DashboardController@autoriseStudent')->name('autoriseStudent');
		Route::post('/createEtudiant','Comptabilite\DashboardController@createEtudiant')->name('createEtudiant');
		Route::get('/createEtudiant',function(){return redirect()->back();});
		Route::post('/updateEtudiant','Comptabilite\DashboardController@updateEtudiant')->name('updateEtudiant');
		Route::get('/updateEtudiant',function(){return redirect()->back();});

	});
});
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/','Section\DashboardController@index')->name('index');
		Route::get('/liste-auditoires','Section\DashboardController@getlistAuditoires')->name('getListAuditoires');
		Route::get('/auditoire/{auditoire}','Section\DashboardController@getListStudent')->name('getListStudent');
		
		Route::get('/enrolerEtudiant/{etudiant}','Section\DashboardController@enrolerEtudiant')->name('enrolerEtudiant');
		Route::get('/destroyEnrolement/{enrole}','Section\DashboardController@destroyEnrolement')->name('!enrolerEtudiant');
		Route::get('enroles/auditoire/{auditoire}','Section\DashboardController@getListStudentEnroler')->name('getListStudentEnroles');
		Route::get('bilan','Section\DashboardController@getBilan')->name('getBilan');
		// Route::post('/createEtudiant','Section\DashboardController@createEtudiant')->name('createEtudiant');
		// Route::get('/createEtudiant',function(){return redirect()->back();});
		// Route::post('/updateEtudiant','Section\DashboardController@updateEtudiant')->name('updateEtudiant');
		// Route::get('/updateEtudiant',function(){return redirect()->back();});

	});
});
Auth::routes();

Route::get('/home',function(){
	return App\Http\Controllers\Helper::redirectToDashboard();
})->name('home');

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    protected $primaryKey = 'idsections';
    
}

app/Http/Controllers/Section/DashboardController.php
<?php

namespace App\Http\Controllers\Section;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\DataTables\Section\ListeAuditoiresDataTable;
use App\DataTables\Section\ListeEtudiantByAuditoireDataTable;
use App\DataTables\Section\ListeEtudiantsEnrolesDataTable;
use App\DataTables\Section\BilanDataTable;
use App\Models\Auditoire;
use App\Models\Etudiant;
use App\Models\Enrole;
use Flashy;
class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
	/*
    * Affiche la liste des auditoires
    * @param $dataTables un dataTable 
    * @return la vue acceuil
    */
    public function index(){
    	return redirect()->route('section.getBilan');
    }

    /*
    * Affiche la liste des auditoires
    * @param $dataTables un dataTable 
    * @return la vue acceuil
    */
    public function getListAuditoires(ListeAuditoiresDataTable $dataTables){
        $section = \App\Models\Section::find(auth()->user()->idsections)->lib;
        return $dataTables->render('section.acceuil',compact('section'));
    }
    /*
    * Affiche la liste des etudiant
    * @param $dataTables un dataTable 
    * @return la vue listeEtudiants
    */
    public function getListStudent(Auditoire $auditoire, ListeEtudiantByAuditoireDataTable $dataTables){
    	return $dataTables->with(['idauditoires'=>$auditoire->idauditoires])->render('section.listeEtudiants',compact('auditoire'));
    }
    /*
    * Enrôler un étudiant
    */
    public function enrolerEtudiant(Etudiant $etudiant){
        Enrole::create([
            'idetudiants' => $etudiant->idetudiants,
            'idusers' => 1,
        ]);  
        // Flashy
        Flashy::success("L'étudiant a été enrôler avec succès");
        return redirect()->back();
    }
    /*
    * Affiche la liste des etudiant enroller
    * @param $dataTables un dataTable 
    * @return la vue listeEtudiants
    */
    public function getListStudentEnroler(Auditoire $auditoire, ListeEtudiantsEnrolesDataTable $dataTables){
        return $dataTables->with(['idauditoires'=>$auditoire->idauditoires,'auditoire'=>$auditoire->lib])->render('section.listeEtudiantsEnroles',compact('auditoire'));
    }
    /*
    * Affiche le bilan de chaque auditoire
    * @param $dataTables un dataTable 
    * @return la vue listeEtudiants
    */
    public function getBilan(BilanDataTable $dataTables){
        return $dataTables->render('section.bilan');
    }

        /*
    * supprimer un etudiant enroller
    * @idetudiants
    */
    public function destroyEnrolement(Enrole $enrole){
        Enrole::where('idenroles',$enrole->idenroles)->delete();
        Flashy::info("L'étudiant est retiré aux enrôlés avec succès");
        return redirect()->back();
    }



    
}

resources/views/section/acceuil.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container"  >
	<div class="row">
        <div class="col-md-12">
         <h2 class="badge badge-pill badge-info">Section : {{ $section }}</h2>   
        </div>
    </div>
     {{-- <hr /> --}}
	<div class="card bg-light mb-3">
	  <div class="card-body" >
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/section/bilan.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/section/listeEtudiants.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<h3>{{ $auditoire->lib }}</h3>
	<a  href="{{ route('section.getListStudentEnroles',$auditoire->idauditoires) }}" type="button" class="btn btn-info">
  		<span class="fa fa-user"> </span> Etudiants enrôlés
	</a><br><br>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/section/listeEtudiantsEnroles.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<h3>Enrôlés : {{ $auditoire->lib }}</h3>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush