routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Auditoire::getBilan();
    return view('test');
});


Route::prefix('comptabilite')->group(function(){
	Route::name('comptabilite.')->group(function () {
		Route::get('/','Comptabilite\DashboardController@index')->name('index');
		Route::get('/auditoire/{auditoire}','Comptabilite\DashboardController@getListStudent')->name('getListStudent');
		
		Route::get('/autorise/{etudiant}','Comptabilite\DashboardController@autoriseStudent')->name('autoriseStudent');
		Route::post('/createEtudiant','Comptabilite\DashboardController@createEtudiant')->name('createEtudiant');
		Route::get('/createEtudiant',function(){return redirect()->back();});
		Route::post('/updateEtudiant','Comptabilite\DashboardController@updateEtudiant')->name('updateEtudiant');
		Route::get('/updateEtudiant',function(){return redirect()->back();});

	});
});
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/','Section\DashboardController@index')->name('index');
		Route::get('/liste-auditoires','Section\DashboardController@getlistAuditoires')->name('getListAuditoires');
		Route::get('/auditoire/{auditoire}','Section\DashboardController@getListStudent')->name('getListStudent');
		
		Route::get('/enrolerEtudiant/{etudiant}','Section\DashboardController@enrolerEtudiant')->name('enrolerEtudiant');
		Route::get('/destroyEnrolement/{enrole}','Section\DashboardController@destroyEnrolement')->name('!enrolerEtudiant');
		Route::get('enroles/auditoire/{auditoire}','Section\DashboardController@getListStudentEnroler')->name('getListStudentEnroles');
		Route::get('bilan','Section\DashboardController@getBilan')->name('getBilan');
		// Route::post('/createEtudiant','Section\DashboardController@createEtudiant')->name('createEtudiant');
		// Route::get('/createEtudiant',function(){return redirect()->back();});
		// Route::post('/updateEtudiant','Section\DashboardController@updateEtudiant')->name('updateEtudiant');
		// Route::get('/updateEtudiant',function(){return redirect()->back();});

	});
});
Auth::routes();

Route::get('/home',function(){
	return App\Http\Controllers\Helper::redirectToDashboard();
})->name('home');

app/Http/Controllers/Comptabilite/DashboardController.php
<?php

namespace App\Http\Controllers\Comptabilite;

use Illuminate\Http\Request;
use App\Http\Requests\UpdateEtudiantComptabiliteRequest;
use App\Http\Requests\CreateEtudiantComptabiliteRequest;
use App\Http\Controllers\Controller;
use App\DataTables\Comptabilite\ListeAuditoiresDataTable;
use App\DataTables\Comptabilite\ListeEtudiantByAuditoireDataTable;
use App\Models\Auditoire;
use App\Models\Etudiant;
use Flashy;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');  
    }
    /*
    * Affiche la liste des auditoires
    * @param $dataTables un dataTable 
    * @return la vue acceuil
    */
    public function index(ListeAuditoiresDataTable $dataTables){
    	return $dataTables->render('comptabilite.acceuil');
    }
    /*
    * Affiche la liste des etudiant
    * @param $dataTables un dataTable 
    * @return la vue listeEtudiants
    */
    public function getListStudent(Auditoire $auditoire, ListeEtudiantByAuditoireDataTable $dataTables){
    	return $dataTables->with(['idauditoires'=>$auditoire->idauditoires])->render('comptabilite.listeEtudiants',compact('auditoire'));
    }
    /*
    * Autorise ou demet un étudiant
    * étudiant demet ne s'affiche pas à la section
    * @param $dataTables un dataTable 
    * @return la vue listeEtudiants
    */
    public function autoriseStudent(Etudiant $etudiant){
    	$etudiant->statut = $etudiant->statut == 0 ? 1 : 0;	
    	$etudiant->save();
    	// Flashy
       $etudiant->statut == 1 ?
        Flashy::info("L'étudiant est autorisé en s'enrôler avec succès")
        : Flashy::info("L'étudiant n'est plus autorisé en s'enrôler");


    	return redirect()->back();
    }
    /*
    * Ajout étudiant
    * @return redirection back
    */
    public function createEtudiant(CreateEtudiantComptabiliteRequest $request){
    	Etudiant::updateOrCreate([
                                    'idetudiants' => $request->data_idetudiants
                                ],
                                [
                                    'matricule' => $request->matricule,
                                    'nom' => $request->nom,
                                    'postnom' => $request->postnom,
                                    'prenom' => $request->prenom,
                                    'idauditoires' => $request->idauditoires,
                                    'frais' => $request->frais,
                                    'idprofils' => $request->profil,
                                    'commentaire' => $request->Commentaire,
                                ]); 
        
  
        Flashy::success('Etudiant ajouté avec succès');
        return redirect()->back();
    }
    /*
    * Edition étudiant
    * @return redirection back
    */
    public function updateEtudiant(UpdateEtudiantComptabiliteRequest $request){
    	Etudiant::find($request->data_idetudiants)->update([
                                    'frais' => $request->data_frais,
                                    'idprofils' => $request->data_profil,
                                    'commentaire' => $request->data_Commentaire,
                                ]);
        

        Flashy::success('Informattion modifiée avec succès');
        return redirect()->back();
    }
}

resources/views/comptabilite/acceuil.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<div class="row">
        <div class="col-md-12">
         <h2 class="badge badge-pill badge-info">Comptabilité | ISPT-KIN</h2>   
        </div>
    </div>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/comptabilite/listeEtudiants.blade.php
@extends('layouts.master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
  <h3>{{ $auditoire->lib }}</h3>
	<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#addModal">
  		<span class="fas fa-user-plus"> </span> Nouveau étudiant
	</button><br><br>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>


	<!-- Modal Edition-->
	<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
	  <div class="modal-header">
	    <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
	    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	      <span aria-hidden="true">&times;</span>
	    </button>
	  </div>
	  <div class="modal-body">
	    {{-- msg d'erreur --}}
	    {{-- Formulaire Edition--}}
	    <form id="etudiantForm" action="{{ route('comptabilite.updateEtudiant') }}" method="POST" name="etudiantForm" class="form-horizontal">
	        @csrf
	       <input type="hidden" name="data_idetudiants" id="data_idetudiants" value="">
	       <div class="form-group">
	              <label for="data_frais"  class="control-label">Frais total</label>
	              <div class="col-sm-12">
	                  <input type="digits"  class="form-control" id="data_frais" name="data_frais"  maxlength="50" >
	              </div>
	        </div>
	        <div class="form-group">
	            <label for="data_profil"  class="control-label">Profil de l'étudiant</label>
	            <div class="col-sm-12">
	            	@inject('Profils','App\Models\Profil')
	               	<select class="form-control" id="data_profil" name="data_profil"   required="required">
	            	@foreach($Profils->get() as $profil)
	               		<option value="{{ $profil->idprofils }}">{{ $profil->lib }}</option>
	               	@endforeach
	               	</select>
	            </div>
	        </div>
	        <div class="form-group">
	            <label for="data_Commentaire" class=" control-label col-form-label">Commentaire</label>
	            <div class="col-12">
	                <textarea class="form-control" name="data_Commentaire" id="data_Commentaire" >
	                	
	                </textarea> 
	            </div>
	        </div>

	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
	    </form>

	  </div>
	</div>
	</div>
	</div>
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ajouter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Creation --}}
        <form id="etudiantFormCreate" action="{{ route('comptabilite.createEtudiant') }}" method="POST" name="etudiantFormCreate" class="form-horizontal_create">
            @csrf
	       <input type="hidden" name="idauditoires" id="idauditoires" value="{{ $auditoire->idauditoires }}">

            <div class="form-group">
                  <label for="matricule"  class="control-label">Matricule</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="matricule" name="matricule"  maxlength="50" required="">
                  </div>
              </div>
              <div class="form-group">
                  <label for="nom"  class="control-label">Nom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="nom" name="nom"  maxlength="50" required="">
                  </div>
              </div>
              <div class="form-group">
                  <label for="postnom"  class="control-label">Postnom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="postnom" name="postnom"  maxlength="50" >
                  </div>
              </div>
              <div class="form-group">
                  <label for="prenom"  class="control-label">Prenom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="prenom" name="prenom"  maxlength="50" >
                  </div>
              </div>
            <div class="form-group">
	              <label for="frais"  class="control-label">Frais total</label>
	              <div class="col-sm-12">
	                  <input type="digits"  class="form-control" id="frais" name="frais"  maxlength="50" >
	              </div>
	        </div>
	        <div class="form-group">
	            <label for="profil"  class="control-label">Profil de l'étudiant</label>
	            <div class="col-sm-12">
	            	@inject('Profils','App\Models\Profil')
	               	<select class="form-control" id="profil" name="profil"   required="required">
	            	@foreach($Profils->get() as $profil)
	               		<option value="{{ $profil->idprofils }}">{{ $profil->lib }}</option>
	               	@endforeach
	               	</select>
	            </div>
	        </div>
	        <div class="form-group">
	            <label for="Commentaire" class=" control-label col-form-label">Commentaire</label>
	            <div class="col-12">
	                <textarea class="form-control" name="Commentaire" id="Commentaire" maxlength="65" >
	                	
	                </textarea> 
	            </div>
	        </div>


        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <button type="submit" class="save btn btn-primary">Enregistrer</button>
        </div>
        </form>
        
      </div>
    </div>
  </div>
</div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}

<script type="text/javascript">
  
  {{-- Ajout étudiant formulaire --}}
  $(document).on('click', '.addModal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');

    $('.modal-title').text('Ajouter');
    // resetmodalData()
    $('.form-horizontal_create').trigger("reset");
    $('.form-horizontal_create').show();
    $('#myModal').modal('show');
    });

  {{-- edition du formulaire --}}
  $(document).on('click', '.edit-modal', function() {
        $('#msgErrors').html('');
          $('#msgErrors').attr('hidden','true');

      $('#footer_action_button').text(" Update");
      $('#footer_action_button').addClass('fa fa-check');
      $('#footer_action_button').removeClass('fa fa-trash');
      $('.actionBtn').addClass('btn-success');
      $('.actionBtn').removeClass('btn-danger');
      $('.actionBtn').removeClass('delete');
      $('.actionBtn').addClass('edit');
      $('.modal-title').text('Modifier');
      $('.deleteContent').hide();
      $('.form-horizontal').show();
      var stuff = $(this).data('info').split(',');
      fillmodalData(stuff)
      $('#myModal').modal('show');
      });

  // remplissage formulaire par les donnée d'une ligne selectionée
  function fillmodalData(details){
      $('#data_idetudiants').val(details[0]);
      // $('#matricule').val(details[1);
      // $('#nom').val(details[2]);
      // $('#postnom').val(details[3]);
      // $('#prenom').val(details[4]);
      $('#data_frais').val(details[5]);
      $('#data_profil').val(details[6]);
      $('#data_Commentaire').val(details[7]);
      }

  function resetmodalData(){
  	  $('#data_idetudiants').val('');
      // $('#matricule').val('');
      // $('#nom').val('');
      // $('#postnom').val('');
      // $('#prenom').val('');
      $('#data_frais').val('');
      $('#data_profil').val('');
      $('#data_Commentaire').val('');
     
      }



  {{-- Suppression  --}}
  $(document).on('click', '.delete-modal', function() {
    $('#footer_action_button').text(" Delete");
    $('#footer_action_button').removeClass('glyphicon-check');
    $('#footer_action_button').addClass('glyphicon-trash');
    $('.actionBtn').removeClass('btn-success');
    $('.actionBtn').addClass('btn-danger');
    $('.actionBtn').removeClass('edit');
    $('.actionBtn').addClass('delete');
    $('.modal-title').text('Delete');
    $('.deleteContent').show();
    $('.form-horizontal').hide();
    var stuff = $(this).data('info').split(',');
    $('.divd').text(stuff[0]);
    $('.dname').html(stuff[1] +" "+stuff[2]);
    $('#myModal').modal('show');
  });

</script>
@endpush