routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/test', function () {
	$data =  App\Models\Auditoire::getBilan();
    return view('test');
});


Route::prefix('comptabilite')->group(function(){
	Route::name('comptabilite.')->group(function () {
		Route::get('/','Comptabilite\DashboardController@index')->name('index');
		Route::get('/auditoire/{auditoire}','Comptabilite\DashboardController@getListStudent')->name('getListStudent');
		
		Route::get('/autorise/{etudiant}','Comptabilite\DashboardController@autoriseStudent')->name('autoriseStudent');
		Route::post('/createEtudiant','Comptabilite\DashboardController@createEtudiant')->name('createEtudiant');
		Route::get('/createEtudiant',function(){return redirect()->back();});
		Route::post('/updateEtudiant','Comptabilite\DashboardController@updateEtudiant')->name('updateEtudiant');
		Route::get('/updateEtudiant',function(){return redirect()->back();});

	});
});
Route::prefix('section')->group(function(){
	Route::name('section.')->group(function () {
		Route::get('/','Section\DashboardController@index')->name('index');
		Route::get('/liste-auditoires','Section\DashboardController@getlistAuditoires')->name('getListAuditoires');
		Route::get('/auditoire/{auditoire}','Section\DashboardController@getListStudent')->name('getListStudent');
		
		Route::get('/enrolerEtudiant/{etudiant}','Section\DashboardController@enrolerEtudiant')->name('enrolerEtudiant');
		Route::get('/destroyEnrolement/{enrole}','Section\DashboardController@destroyEnrolement')->name('!enrolerEtudiant');
		Route::get('enroles/auditoire/{auditoire}','Section\DashboardController@getListStudentEnroler')->name('getListStudentEnroles');
		Route::get('bilan','Section\DashboardController@getBilan')->name('getBilan');
		// Route::post('/createEtudiant','Section\DashboardController@createEtudiant')->name('createEtudiant');
		// Route::get('/createEtudiant',function(){return redirect()->back();});
		// Route::post('/updateEtudiant','Section\DashboardController@updateEtudiant')->name('updateEtudiant');
		// Route::get('/updateEtudiant',function(){return redirect()->back();});

	});
});
Auth::routes();

Route::get('/home',function(){
	return App\Http\Controllers\Helper::redirectToDashboard();
})->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/default.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>

    @yield('stylesheet1')
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @yield('stylesheet')
    <!-- Coustom styleSheet--->
    @stack('stylesheets')


</head>

  <body>

@include('layouts.partials._header')
{{-- @include('communes.layouts.partials._header_img') --}}
@include('layouts.partials._nav')
<br>
    <div class="container-fluid clearfix">
        <div class="container">
            @include('partials._msgFlash')
        </div>
@yield('content')
    </div>
@include('layouts.partials._footer')



    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('bootstrap/js/bootstrap.bundle.min.js') }}></script>
    <script type="text/javascript">
        $(function () {
                      $('[data-toggle="popover"]').popover()
                    })
    </script>
  
    <!-- this page js -->

@stack('scripts')

  </body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/pricing/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:41:46 GMT -->
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>
	<!-- BOOTSTRAP STYLES-->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet"> --}}
    @yield('stylesheet1')
     <!-- FONTAWESOME STYLES-->
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
     <!-- MORRIS CHART STYLES-->
    
        <!-- CUSTOM STYLES-->
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet" />
    @yield('stylesheet')

    @stack('stylesheets')

     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
     <!-- TABLE STYLES-->

    <!-- Date et heure -->
    <script type="text/javascript" src="{{ asset('js/date-heure.js') }}"></script>

</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">

         {{--        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button> --}}


         {{--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button> --}}
                <a class="navbar-brand mx-auto d-block" href="{{ route('home') }}">ISPT - KIN</a> 
            </div>
            <div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;">
            <h2 class="badge badge-info">{{ \App\Http\Controllers\Helper::getUserRole() }}</h2>   
            <span id="date_heure"></span> &nbsp; 
            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn btn-danger square-btn-adjust">Déconnexion</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
            </div>
        </nav>   
           <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side sidebar-nav" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav " id="main-menu">
    				<li class="text-center mx-auto d-block sidebar-item">
                        <img style="max-width: 60%" src="{{ asset('/img/logoIspt.gif') }}" class="user-image img-responsive img-fluid"/>
    				</li>
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="{{ route('home') }}"><i class="fas fa-tachometer-alt fa-2x"></i> Tableau de bord</a>
                    </li>
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="{{ route('section.getListAuditoires') }}"><i class=" fas fa-th-list fa-2x"></i> Enrôlements</a>
                    </li>
                    <li>
                        <a class="sidebar-link has-arrow waves-effect waves-dark"  href="#"><i class=" fas fa-user fa-2x"></i> Mon profil</a>
                    </li>
                   
				{{-- 	<!-- Multi link -->
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-2x"></i> Enrôlements<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Enrôler étudiant</a>
                            </li>
                            <li>
                                <a href="#">Liste des enrôlés</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>

                                </ul>
                               
                            </li>
                        </ul>
                    </li>  --}} 
                </ul>
               
            </div>
            
        </nav>  
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
          
                     {{-- <a href=""><i class="fas fa-arrow-circle-left fa-2x"></i></a>    --}}

            <div id="page-inner" style="background-color: : #F3F3F3">
               {{--  <div class="row">
                    <div class="col-md-12">
                     <h2 class="btn btn-success">{{ \App\Http\Controllers\Helper::getUserRole() }}</h2>   
                        <h5>home Jhon Deo , Love to see you back. </h5>
                    </div>
                </div> --}}
                 {{-- <hr /> --}}
                @yield('content')
                 <!-- /. ROW  -->
            </div>
               
            @include('layouts.partials._footer')
        </div>
             <!-- /. PAGE INNER  -->

    </div>
         <!-- /. PAGE WRAPPER  -->
     <!-- /. WRAPPER  -->

    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>

      <!-- BOOTSTRAP SCRIPTS -->
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('bootstrap/js/bootstrap.bundle.min.js') }}></script>


    <!-- METISMENU SCRIPTS -->
    <script src="{{ asset("js/jquery.metisMenu.js") }}"></script>

    @stack('scripts')


         <!-- CUSTOM SCRIPTS -->
    <script src="{{ asset("js/custom.js") }}"></script>
    <script src="{{ asset("js/raphael-2.1.0.min.js") }}"></script>
    <script src="{{ asset("js/morris.js") }}"></script>
    <script type="text/javascript">window.onload = date_heure('date_heure');</script>


    <script type="text/javascript">
        $(function () {
                      $('[data-toggle="popover"]').popover()
                    })
    </script>
    
       {{-- PACKAGES --}}
    <!--Flashy -->
    @include('flashy::message')
</body>
</html>